"""Assemble the EVIDENCE-upgraded submission (§150 block -> the actual file).

Keeps risk_score + predicted_behavior BYTE-IDENTICAL to the 0.82082 best (seq_v2_submission.csv);
swaps ONLY evidence_hand_1..5, regenerated by the evidence ranker trained on HAND_FEATS + contextualized
per-hand seq embedding (the confirmed +0.059 in-harness OOF MAP@5 block).

Steps:
  1. build EVAL contextualized per-hand emb (windowed, ALL 112,540 eval pairs) via seq_ctx_evidence.
  2. train the evidence ranker (HAND_FEATS + ctx_emb, is_evidence target) on ALL dev positives
     (mirrors pipeline rank_models_full: 2 seeds x 400 rounds binary), like the baseline but +ctx.
  3. score eval hands, pick top-5 per pair (host ordering: hand_score desc, pot_bb desc, hand_id asc).
  4. swap evidence columns into the 0.82082 base; verify risk+behavior identical, evidence valid.

Run:  python -m anchor_repro.seq_evidence_submit
"""
from __future__ import annotations
import time, numpy as np, polars as pl, pandas as pd, lightgbm as lgb
from pathlib import Path
from anchor_repro.seq_evidence import build_dh, HAND_FEATS, HAND_PARAMS, HAND_SEEDS, HAND_ROUNDS
from anchor_repro.seq_ctx_evidence import build_aligned, embed_ctx, CTXCOLS
STEP3=Path("outputs/poker_collusion/hosen42_step3"); SEQ=STEP3/"edge"/"seq"
BASE_SUB=Path("outputs/poker_collusion/seq_v2_submission.csv")   # the 0.82082 best
OUT_SUB=Path("outputs/poker_collusion/seq_evidence_submission.csv")
T0=time.time()
def log(m): print(f"[{time.time()-T0:6.0f}s] {m}",flush=True)

def main():
    # ---- 1. eval ctx emb (windowed, all eval pairs) ----
    build_aligned(STEP3/"eval_pair_hands.parquet","evaluation",SEQ/"seq_aligned_eval.parquet")
    embed_ctx("evaluation",SEQ/"seq_aligned_eval.parquet",SEQ/"seq_ctx_emb_eval.parquet")  # no keep_pairs

    # ---- 2. train evidence ranker on ALL dev positives (HAND_FEATS + ctx_emb) ----
    dh=build_dh()
    if not (SEQ/"seq_ctx_emb_dev.parquet").exists():   # regenerate dev ctx emb if missing (fast: labelled pairs only)
        build_aligned(STEP3/"dev_pair_hands.parquet","development",SEQ/"seq_aligned_dev.parquet")
        embed_ctx("development",SEQ/"seq_aligned_dev.parquet",SEQ/"seq_ctx_emb_dev.parquet",
                  keep_pairs=set(dh["pair_id"].to_list()))
    demb=pl.read_parquet(SEQ/"seq_ctx_emb_dev.parquet")
    dh=dh.join(demb,on=["pair_id","hand_idx"],how="left").to_pandas()
    dh[CTXCOLS]=dh[CTXCOLS].fillna(0.0).astype("float32"); dh[HAND_FEATS]=dh[HAND_FEATS].astype("float32")
    pos_mask=(dh["label"]==1).to_numpy()
    FEATS=HAND_FEATS+CTXCOLS
    log(f"training evidence ranker on {int(pos_mask.sum()):,} positive-pair hands, {len(FEATS)} feats")
    models=[lgb.train({**HAND_PARAMS,"seed":sd},
                      lgb.Dataset(dh.loc[pos_mask,FEATS],dh.loc[pos_mask,"is_evidence"].astype(int)),
                      num_boost_round=HAND_ROUNDS) for sd in HAND_SEEDS]

    # ---- 3. score eval hands, top-5 per pair (STREAMED: 9.6M x 292 frame OOMs on 15GB RAM) ----
    n_eval=pl.scan_parquet(STEP3/"eval_hand_features.parquet").select(pl.len()).collect().item()
    log(f"streaming-score {n_eval:,} eval hands (ctx emb float16, per-chunk join)")
    eemb=pl.read_parquet(SEQ/"seq_ctx_emb_eval.parquet")   # ~3.7GB float16, loaded once
    ehf=pl.scan_parquet(STEP3/"eval_hand_features.parquet")
    CH=1_500_000; keep_cols=["pair_id","hand_id","pot_bb"]
    # pot_bb is already in HAND_FEATS -> dedupe the select to avoid polars DuplicateError
    sel_extra=[c for c in ["pair_id","hand_id","pot_bb","hand_idx"] if c not in HAND_FEATS]
    parts=[]
    for s in range(0,n_eval,CH):
        chunk=(ehf.slice(s,CH).select(sel_extra+HAND_FEATS).collect()
               .join(eemb,on=["pair_id","hand_idx"],how="left"))
        cp=chunk.to_pandas()
        for c in CTXCOLS:
            if c not in cp.columns: cp[c]=np.float32(0.0)
        cp[CTXCOLS]=cp[CTXCOLS].fillna(0.0).astype("float32"); cp[HAND_FEATS]=cp[HAND_FEATS].astype("float32")
        hs=np.mean([m.predict(cp[FEATS]) for m in models],axis=0)
        part=cp[keep_cols].copy(); part["hand_score"]=hs
        parts.append(part)
        del chunk,cp; log(f"  scored {min(s+CH,n_eval):,}/{n_eval:,}")
    del eemb
    ehp=pd.concat(parts,ignore_index=True); del parts
    log("eval scored; building top-5 per pair (host ordering)")
    top=(ehp.sort_values(["pair_id","hand_score","pot_bb","hand_id"],ascending=[True,False,False,True],kind="mergesort")
         .groupby("pair_id")["hand_id"].apply(lambda s:list(s.head(5))))
    ev=pd.DataFrame({"pair_id":top.index})
    for i in range(5):
        ev[f"evidence_hand_{i+1}"]=[ (v[i] if i<len(v) else "NO_EVIDENCE") for v in top.values ]

    # ---- 4. swap evidence into the 0.82082 base (risk+behavior byte-identical) ----
    base=pd.read_csv(BASE_SUB); base["pair_id"]=base["pair_id"].astype(str); ev["pair_id"]=ev["pair_id"].astype(str)
    EVCOLS=[f"evidence_hand_{i}" for i in range(1,6)]
    out=base.drop(columns=EVCOLS).merge(ev,on="pair_id",how="left")
    # any pair with no eval hands (shouldn't happen) -> keep base evidence as fallback
    miss=out["evidence_hand_1"].isna()
    if miss.any():
        log(f"WARN {miss.sum()} pairs missing new evidence -> fallback to base")
        fb=base.set_index("pair_id")[EVCOLS]
        for c in EVCOLS: out.loc[miss,c]=out.loc[miss,"pair_id"].map(fb[c])
    out=out[list(base.columns)]  # restore exact column order

    # ---- verify ----
    assert len(out)==len(base) and (out["pair_id"].values==base["pair_id"].values).all(), "pair set/order changed"
    assert (out["risk_score"].values==base["risk_score"].values).all(), "risk changed!"
    assert (out["predicted_behavior"].values==base["predicted_behavior"].values).all(), "behavior changed!"
    changed=(out[EVCOLS].values!=base[EVCOLS].values).any(axis=1).sum()
    # evidence cells non-empty, no per-row hand-id repeats
    for _,row in out[EVCOLS].head(2000).iterrows():
        cells=[c for c in row.tolist() if isinstance(c,str) and c and c!="NO_EVIDENCE"]
        assert len(cells)==len(set(cells)), "duplicate evidence hand in a pair"
    out.to_csv(OUT_SUB,index=False)
    log(f"wrote {OUT_SUB.name}: {len(out):,} rows; risk+behavior IDENTICAL; evidence changed on {changed:,}/{len(out):,} pairs")
    return 0

if __name__=="__main__":
    raise SystemExit(main())
